# Generated by Django 3.0 on 2020-01-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=155)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
