# Generated by Django 3.0 on 2020-01-28 20:53

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200122_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
    ]
