# Generated by Django 3.0 on 2020-01-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
