# Generated by Django 3.0 on 2019-12-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='timsestamp',
            new_name='timestamp',
        ),
    ]
