# Generated by Django 3.0 on 2019-12-07 20:56

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20191207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=255, validators=[tweets.validators.validate_content]),
        ),
    ]
