# Generated by Django 3.0 on 2020-01-22 14:26

from django.db import migrations, models
import tweets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tweets.utils.get_tweet_image_name),
        ),
    ]
