# Generated by Django 3.0 on 2020-03-21 17:31

from django.db import migrations
import django_resized.forms
import tweets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20200122_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=tweets.utils.get_tweet_image_name),
        ),
    ]
